# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dU9FbGep26YN7UZwl_lTPZItW6fpMvR
"""

import pandas as pd
import numpy as nu

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

df.shape

df.isnull().sum()

drop_col = df.isnull().sum()[df.isnull().sum()>(50/100 * df.shape[0])]
drop_col

x = df.isnull().sum()
drop_col = x[x>(50/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=False)
df.isnull().sum()

df.fillna(df.mean(), inplace = False)
df.isnull().sum()

df['Embarked'].describe()

df['Embarked'].fillna('C',inplace=True)

df.isnull().sum()

df['Embarked'].describe()

df.corr()

df[['Parch','Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

df['Embarked'].fillna('C',inplace=True)

df.isnull().sum()

df.groupby(['Ticket'])['Survived'].mean()

df.corr()

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()